# Generated by Django 5.1.1 on 2024-09-18 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Averages',
            fields=[
                ('averages', models.CharField(db_column='averages', max_length=45, primary_key=True, serialize=False)),
                ('cse', models.DecimalField(decimal_places=2, max_digits=10)),
                ('it', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ece', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('csm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aiml', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mec', models.DecimalField(decimal_places=2, max_digits=10)),
                ('civ', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aids', models.DecimalField(decimal_places=2, max_digits=10)),
                ('college', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'averages',
            },
        ),
        migrations.CreateModel(
            name='HomeAnouncement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text_input', models.CharField(max_length=200)),
                ('date_input', models.DateField()),
            ],
            options={
                'db_table': 'home_anouncement',
            },
        ),
        migrations.CreateModel(
            name='StudentScores',
            fields=[
                ('roll_no', models.CharField(db_column='roll_no', max_length=10, primary_key=True, serialize=False)),
                ('hackerrank', models.TextField(blank=True, db_column='hackerrank', null=True)),
                ('hackerrank_score', models.IntegerField(db_column='hackerrank_score')),
                ('codeforces', models.TextField(blank=True, db_column='codeforces', null=True)),
                ('codeforces_score', models.IntegerField(db_column='codeforces_score')),
                ('codechef', models.TextField(blank=True, db_column='codechef', null=True)),
                ('codechef_score', models.IntegerField(db_column='codechef_score')),
                ('spoj', models.TextField(blank=True, db_column='spoj', null=True)),
                ('spoj_score', models.IntegerField(db_column='spoj_score')),
                ('interviewbit', models.TextField(blank=True, db_column='interviewbit', null=True)),
                ('interviewbit_score', models.IntegerField(db_column='interviewbit_score')),
                ('leetcode', models.TextField(blank=True, db_column='leetcode', null=True)),
                ('leetcode_score', models.IntegerField(db_column='leetcode_score')),
                ('gfg', models.TextField(blank=True, db_column='gfg', null=True)),
                ('gfg_score', models.IntegerField(db_column='gfg_score')),
                ('overall_score', models.IntegerField(db_column='overall_score')),
                ('daily_scores', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student_scores',
            },
        ),
        migrations.CreateModel(
            name='StudentMaster',
            fields=[
                ('rank', models.IntegerField(blank=True, db_column='rank', null=True)),
                ('roll_no', models.OneToOneField(db_column='roll_no', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.studentscores')),
                ('name', models.CharField(db_column='name', max_length=39)),
                ('course', models.CharField(blank=True, db_column='course', max_length=7, null=True)),
                ('year', models.IntegerField(blank=True, db_column='year', null=True)),
                ('branch', models.CharField(blank=True, db_column='branch', max_length=10, null=True)),
                ('sec', models.CharField(blank=True, db_column='sec', max_length=1, null=True)),
                ('hackerrank_username', models.CharField(blank=True, db_column='hackerrank_username', max_length=48, null=True)),
                ('codeforces_username', models.CharField(blank=True, db_column='codeforces_username', max_length=40, null=True)),
                ('codechef_username', models.CharField(blank=True, db_column='codechef_username', max_length=92, null=True)),
                ('spoj_username', models.CharField(blank=True, db_column='spoj_username', max_length=22, null=True)),
                ('interviewbit_username', models.CharField(blank=True, db_column='interviewbit_username', max_length=42, null=True)),
                ('leetcode_username', models.CharField(blank=True, db_column='leetcode_username', max_length=29, null=True)),
                ('gfg_username', models.CharField(blank=True, db_column='gfg_username', max_length=48, null=True)),
            ],
            options={
                'db_table': 'student_master',
            },
        ),
    ]
